### ISSUE TITLE
logger can cause worker to crash with print

### ISSUE THREAD

**Issue by azanegin** [IntelLabs/kafl.fuzzer#1]
I'm running around 20 workers with many `hprintf` calls. Doing this in tmux over ssh on a remote machine.

Sometimes, calls to `print` in kafl's logging facilities would raise `BlockingIOError` due to inability to do I/O without blocking. A small issue, but the call is made in the context of a worker. So worker dies.

Catching exception and retrying allowed my setup to work normally - as a quick hack. But I think it is not the optimal way to fix this. 

Instead, do you think its possible to make kAFL use standard python logging library? or at least move this things out of worker's context.

**Comment by il-steffen** [comment]
Sorry I didn't see your post. We've seen this issue initially with the logging solution but I thought it had been fixed.

Is there anything special in your setup? I regularly run with 32 or 64 workers via ssh/tmux, also typically not with a log of verbosity enabled (run debug/verbosity only with few VMs as it quickly fills your disk)

**Comment by azanegin** [comment]
Nothing really special, just a lot of verbosity - I think I enabled everything I found in kAFL? Plus my agent setup is very verbose. 

I think this can be mitigated. If you do not mind, I can provide patches to move it to standard python logger.

**Comment by il-steffen** [comment]
I'd be happy to replace a custom module with the standard lib. I think we did not use it back then because the handling of log levels did not match our preferences. Mainly, please ensure we keep an easy way to prefix a worker/module ID and WARN/ERROR level should go to stderr as well as possible enabled logfile.
https://github.com/IntelLabs/kafl.fuzzer/blob/master/kafl_fuzzer/common/logger.py#L14

Note that agent logging is completely seperate via qemu.py/handle_hprintf()..
