### ISSUE TITLE
Remove qemu_append from the default configuration

### ISSUE THREAD

**Issue by Wenzel** [IntelLabs/kafl.fuzzer#64]
The default configuration kafl.fuzzer configuration file specify a `qemu_append` option.
https://github.com/IntelLabs/kafl.fuzzer/blob/master/kafl_fuzzer/common/config/default_settings.yaml#L27

This is only useful when fuzzing a kernel specified with `--kernel`.
This setting is target specific and should be removed from the default config.

In fact when fuzzing a bios:
![image](https://user-images.githubusercontent.com/964610/236502661-d0e83e03-4786-4eb5-b160-5a9a0be670c6.png)

**Comment by il-steffen** [comment]
You need it when booting Linux, so I think the question is which one is the more common default?

We could also modify qemu.py to supply the append option only when --kernel is specified. The problem is that users may also have `"qemu_base = -kernel xyz"` or `qemu_extra = "-bios foo"`

Currently, there should be a kafl.yaml in the edk2 example folder that sets `qemu_append` option to empty string, and I think qemu.py is looking out for that.

**Comment by Wenzel** [comment]
> Currently, there should be a kafl.yaml in the edk2 example folder that sets qemu_append option to empty string, and I think qemu.py is looking out for that.

Ideally this shouldn't be required.

> We could also modify qemu.py to supply the append option only when --kernel is specified.

I think this is the right approach. 👍 

> The problem is that users may also have "qemu_base = -kernel xyz" or qemu_extra = "-bios foo"

Then we should redirect the user to the right config options for the fuzzer, they shouldn't use `qemu_base` or `qemu_extra` to specify either the kernel or the bios.

**Comment by Wenzel** [comment]
closed by #78
